server:
  tomcat:
    uri-encoding: UTF-8
  context-path: /api

#聚合数据彩票数据接口key
polymerization:
  lottery:
    key: 填写你自己申请的聚合数据key

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath:/mapper/*.xml

logging:
  level: debug

spring:
  profiles:
    active: local
  mail:
    host: 
    username: 
    password: 
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            trust: 
  thymeleaf:
    # 禁用缓存
    cache: false
    mode: HTML5
    encoding: UTF-8
    suffix: .html

mail:
  fromMail:
    addr: 